# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import qrng_pb2 as proto_dot_qrng__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/qrng_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuantumRNGStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRandomBytes = channel.unary_unary(
                '/qrng.QuantumRNG/GetRandomBytes',
                request_serializer=proto_dot_qrng__pb2.RandomRequest.SerializeToString,
                response_deserializer=proto_dot_qrng__pb2.RandomResponse.FromString,
                _registered_method=True)


class QuantumRNGServicer(object):
    """Service definition
    """

    def GetRandomBytes(self, request, context):
        """Get quantum random bytes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumRNGServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRandomBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRandomBytes,
                    request_deserializer=proto_dot_qrng__pb2.RandomRequest.FromString,
                    response_serializer=proto_dot_qrng__pb2.RandomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qrng.QuantumRNG', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qrng.QuantumRNG', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuantumRNG(object):
    """Service definition
    """

    @staticmethod
    def GetRandomBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qrng.QuantumRNG/GetRandomBytes',
            proto_dot_qrng__pb2.RandomRequest.SerializeToString,
            proto_dot_qrng__pb2.RandomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
