# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/qrng.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/qrng.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/qrng.proto\x12\x04qrng\"\"\n\rRandomRequest\x12\x11\n\tnum_bytes\x18\x01 \x01(\r\"D\n\x0eRandomResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\t2I\n\nQuantumRNG\x12;\n\x0eGetRandomBytes\x12\x13.qrng.RandomRequest\x1a\x14.qrng.RandomResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.qrng_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANDOMREQUEST']._serialized_start=26
  _globals['_RANDOMREQUEST']._serialized_end=60
  _globals['_RANDOMRESPONSE']._serialized_start=62
  _globals['_RANDOMRESPONSE']._serialized_end=130
  _globals['_QUANTUMRNG']._serialized_start=132
  _globals['_QUANTUMRNG']._serialized_end=205
# @@protoc_insertion_point(module_scope)
